name: CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    uses: KryptoExchange/devops/.github/workflows/backend-jvm-reusable.yml@main
    with:
      service_name: trading-gateway
      app_key: trading-gateway
      image_name: trading-gateway
    secrets: inherit
